server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  servlet:
    session:
      cookie:
        name: AUTH_JSESSIONID
  port: 9000

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

config:
  issuer-uri: https://sso.fuckingamazing.exchange
  redirect-uri: https://fuckingamazing.exchange